### ISSUE TITLE
[PE-D][Tester A] Duplicate session problem

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103-W14-1/tp#154]
When I open 2 sessions of the app, and i delete a person from the first session, if i try to edit that person from the 2nd session (who is supposed to be already deleted), I somehow can! And when I type list the deleted person is still there! 

![Screenshot 2023-11-03 163419.png](https://raw.githubusercontent.com/AustinHuang1203/ped/main/files/629f9be2-5f35-4305-9614-572b03455804.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: AustinHuang1203/ped#9

**Comment by zhanyang01** [comment]
We added preventive measures in the UG as fixing it if even possible will certainly violate feature freeze
